### ISSUE TITLE
stand alone or use in php-crud-api api.php?

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-sp-api#3]
how do you intend for this file to be used? it looks stand alone. Can you provide more information maybe in the readme?

**Comment by mevdschee** [comment]
Thank you for your question. How you use it is totally up to you. It can easily be integrated in other scripts.

**Comment by f0rever-johnson** [comment]
Sorry to reopen. How would I integrate this script with php-crud-api v2 so I can take advantage of the jwtoauth security options?

**Comment by mevdschee** [comment]
>How would I integrate this script with php-crud-api v2

This is not supported, but there is a promising PR on the project that you may like:

https://github.com/mevdschee/php-crud-api/pull/729
